---
title: "Appendix"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(rvest)
library(readr)
library(tidyverse)
library(caret)
library(FNN)
library(wesanderson)
library(knitr)
library(kableExtra)
library(owidR)
library(RCurl)
```


## Web scraping
# Load Covid mortality 
```{r}
html_covid_rates <- read_html("https://www.statista.com/statistics/1104709/coronavirus-deaths-worldwide-per-million-inhabitants/")
tab_covid_rates_raw <- (html_covid_rates |> html_nodes("table"))[[1]] |> html_table()
df_covid_rates <- tab_covid_rates_raw |>
  mutate(Total_cases= as.numeric(gsub(",", "", `Confirmed cases (absolute)`)),
         Total_deaths=as.numeric(gsub(",", "", `Confirmed deaths (absolute)`)), 
         Pop_millions= as.numeric(gsub(",", "", `Population (in millions)`)), 
         Country=Characteristic) |>
  select(Country, Total_cases, Total_deaths, Pop_millions)

df_covid_rates

```

# Load vaccination counts
```{r}
url <- getURL("https://covid.ourworldindata.org/data/owid-covid-data.csv")
tab_vax_rates_raw <- read.csv(text = url)
df_vax_rates <- tab_vax_rates_raw |>
  select(location, date, people_fully_vaccinated, continent) |>
  filter(!is.na(people_fully_vaccinated)) |>
  group_by(location, continent) |>
  summarise(fully_vax_count= max(people_fully_vaccinated)) |>
  rename(Country =location, Continent=continent) 

df_vax_rates

```


# Load proportion of the population above 65
```{r}
html_above_65 <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_age_structure")
tab_above_65_raw <- html_table(html_node(html_above_65, ".wikitable"), fill = T)
colnames(tab_above_65_raw) <- tab_above_65_raw[1, ] 

df_above_65<- tab_above_65_raw[-c(1,2),] |>
  select(Country, `Over 65`) |>
  rename(Percent_Over_65 =`Over 65`) |>
  mutate(Percent_Over_65= parse_number(Percent_Over_65))


df_above_65
  
```

# Load Population density 
```{r}
html_pop_density <- read_html("https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population_density")
tab_pop_density_raw <- html_table(html_node(html_pop_density, ".wikitable"), fill = T)
colnames(tab_pop_density_raw) <- tab_pop_density_raw[1, ]

df_pop_density <- tab_pop_density_raw[-1,] |>
  select(`Country, territory or dependency`, `/km2`) |>
  rename(Country =`Country, territory or dependency`, km2 = `/km2`) |>
  mutate(km2= as.numeric(gsub(",", "", km2)))

df_pop_density
  
```



# Load GDP per capita
```{r}
html_GDP_per_capita <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)_per_capita")
tab_GDP_per_capita_raw <- html_table(html_node(html_GDP_per_capita, ".wikitable"), fill = T)
colnames(tab_GDP_per_capita_raw) <- tab_GDP_per_capita_raw[1, ]

df_GDP_per_capita <- (tab_GDP_per_capita_raw[-1,] |>
  select(`Country/Territory`, 5) |>
  rename(Country=`Country/Territory`, GDP_per_capita = Estimate)|>
  mutate(GDP_per_capita= as.numeric(gsub(",", "", GDP_per_capita)),
         Country= str_trim(gsub("\\*", "", Country) ) ))[-1,]

df_GDP_per_capita
```

# Load obesity rates
```{r}
html_obesity_rates <- read_html("https://en.wikipedia.org/wiki/List_of_sovereign_states_by_obesity_rate")
tab_obesity_rates_raw <- html_table(html_node(html_obesity_rates, ".wikitable"), fill = T)

df_obesity_rates <- tab_obesity_rates_raw |>
  rename(Obesity_rate=`Obesity rate (%)`)

df_obesity_rates
```


# Load cardiovascular disease rate
```{r}
tab_CVD_rate_raw <- owid("cardiovascular-disease-death-rates")
df_CVD_rate <- tab_CVD_rate_raw |>
  rename(Country =entity, cvd_death_rate="Deaths - Cardiovascular diseases - Sex: Both - Age: Age-standardized (Rate)") |>
  group_by(Country) |>
  filter(year==max(year), !is.na(cvd_death_rate)) |>
  select(Country, cvd_death_rate) 

df_CVD_rate

```


# format country names 
```{r}
# df_covid_rates
df_covid_rates$Country <- str_replace_all(df_covid_rates$Country, "\\p{No}", "")
df_covid_rates$Country <- gsub('USA', 'United States', df_covid_rates$Country)
df_covid_rates$Country <- gsub('France', 'France', df_covid_rates$Country)
df_covid_rates$Country <- gsub('United Kingdom', 'United Kingdom', df_covid_rates$Country)
df_covid_rates$Country <- gsub('Netherlands', 'Netherlands', df_covid_rates$Country)
df_covid_rates$Country <- gsub('Timor-Leste', 'Timor', df_covid_rates$Country)
df_covid_rates$Country <- gsub("Congo \\(Kinshasa)", "Democratic Republic of Congo", df_covid_rates$Country)
df_covid_rates$Country <- gsub('Congo \\(Brazzaville)', 'Congo', df_covid_rates$Country)
df_covid_rates$Country <- gsub("Czechia", "Czech Republic", df_covid_rates$Country)

# df_vax_rates
df_vax_rates$Country <- gsub("Czechia", "Czech Republic", df_vax_rates$Country)

# df_above_65
df_above_65$Country <- gsub('Democratic Republic of the Congo'  , 'Democratic Republic of Congo', df_above_65$Country)
df_above_65$Country <- gsub('Republic of the Congo'  , 'Congo', df_above_65$Country)
df_above_65$Country <- gsub("Timor-Leste"  , "Timor", df_above_65$Country)
df_above_65$Country <- gsub("Ivory Coast"  , "Cote d'Ivoire", df_above_65$Country)
df_above_65$Country <- gsub("Eswatini \\(Swaziland)"  , "Eswatini", df_above_65$Country)

# df_pop_density
df_pop_density$Country <- gsub('DR Congo'  , 'Democratic Republic of Congo', df_pop_density$Country)
df_pop_density$Country <- gsub('Cyprus \\[note 5]'  , 'Cyprus', df_pop_density$Country)
df_pop_density$Country <- gsub('Russia \\[note 12]'  , 'Russia', df_pop_density$Country)
df_pop_density$Country <- gsub('Ukraine \\[note 9]'  , 'Ukraine', df_pop_density$Country)
df_pop_density$Country <- gsub('Ivory Coast'  , "Cote d'Ivoire", df_pop_density$Country)
df_pop_density$Country <- gsub('East Timor'  , 'Timor', df_pop_density$Country)

# GDP per capita
df_GDP_per_capita$Country <- gsub('East Timor'  , 'Timor', df_GDP_per_capita$Country)
df_GDP_per_capita$Country <- gsub('DR Congo'  , 'Democratic Republic of Congo', df_GDP_per_capita$Country)
df_GDP_per_capita$Country <- gsub('Ivory Coast'  , "Cote d'Ivoire", df_GDP_per_capita$Country)


# obesity rates
df_obesity_rates$Country <- gsub('Timor-Leste'  , 'Timor', df_obesity_rates$Country)
df_obesity_rates$Country <- gsub('Democratic Republic of the Congo'  , 'Democratic Republic of Congo', df_obesity_rates$Country)
df_obesity_rates$Country <- gsub('Republic of the Congo'  , 'Congo', df_obesity_rates$Country)
df_obesity_rates$Country <- gsub("Ivory Coast"  , "Cote d'Ivoire", df_obesity_rates$Country)

# df_CVD_rate
df_CVD_rate$Country <- gsub("Czechia", "Czech Republic", df_CVD_rate$Country)
```


# data wrangling: join tables
```{r}
# join and transform data to create the analysis-ready dataframe 
analysis_df <- left_join(df_covid_rates, df_vax_rates) |>
  left_join(df_above_65)|>
  left_join(df_pop_density)|>
  left_join(df_GDP_per_capita)|>
  left_join(df_obesity_rates)|>
  left_join(df_CVD_rate)

analysis_df[which(is.na(analysis_df$Continent)),]$Continent <- c("Asia","Africa")

# write.csv(analysis_df, "analysis_df.csv")

analysis_df
```

# Exploratory analysis
```{r, message=FALSE,results='asis'}
# Exploratory 
analysis_df <- read.csv("analysis_df.csv")

prop_per_continent <- analysis_df |>
  group_by(Continent)|>
  summarize("Cumulative cases"= sum(Total_cases), 
            "Cumulative deaths"= sum(Total_deaths),
            "Cases per million" = round(sum(Total_cases)/sum(Pop_millions)), 
            "Deaths per million" = round(sum(Total_deaths)/sum(Pop_millions)), 
            "Population (in millions)" = round(sum(Pop_millions)))

prop_per_continent <- rbind(prop_per_continent, c("Total", colSums(prop_per_continent[,-1])))

prop_per_continent[,-1] <- sapply( prop_per_continent[,-1], as.numeric )


knitr::kable(prop_per_continent, 
             caption ="Table 1. Cumulative and per million number of Covid-19 cases and Deaths per continent",
             format.args = list(big.mark = ",")) %>%
  kable_styling(font_size = 15,
                bootstrap_options = c("striped", "hover", "condensed")) 



ggplot(prop_per_continent[-1,], aes(x=Continent, y=`Deaths per million`, fill=Continent))+
  geom_bar(width = 1, stat = "identity")+ 
  scale_fill_manual(values =c(wes_palette("Moonrise3")[-c(3,4)],wes_palette("Cavalcanti1")[c(2,4,5)]))+
  theme_classic()+
  ylab("Mortality rate (deaths per million)")+
  ggtitle("Mortality rate per continent")

```


# RESULTS: Data Analysis

```{r, message=FALSE,results='asis', warning=FALSE}

analysis_df <- read.csv("analysis_df.csv")

# Run the analysis: linear regression
mod <- lm(Total_deaths ~ Total_cases+ fully_vax_count+ Pop_millions+Percent_Over_65 + km2+ GDP_per_capita + Obesity_rate  + cvd_death_rate, analysis_df)
# check assumptions through diagnostic plots 
par(mfrow=c(2,2)) 
plot(mod)

# check results 
mod_results <- as.tibble(summary(mod)$coef) |>
  mutate(Estimate=round(Estimate,3))|>
  rename("P-value"=`Pr(>|t|)`)|>
  select(-`t value`) |>
  mutate(Variable= c("Intercept","Number of cases", "Number fully vaccinated", "Population (millions)", "Percentage over65" , "Population density (km2)","GDP per capita" , "Obesity rate (%)" ,"CVD death rate"), .before=Estimate)


knitr::kable(mod_results, 
             caption ="Table 2. Exponentiated Linear regression coefficients with p-values",
             format.args = list(big.mark = ",")) %>%
  kable_styling(font_size = 15,
                bootstrap_options = c("striped", "hover", "condensed")) 

# plot predicted vs observed values to determine the fit of the model
df_true_pred <- data.frame(true= analysis_df$Total_deaths, predict=round((predict(mod, analysis_df))))

df_true_pred |>
ggplot(aes(x=true, y=predict))+
  geom_point()+
  theme_classic()+
  geom_abline(intercept = 0, slope = 1, colour = "red")+
  ylab("Predicted Cumulative death counts")+
  xlab("True Cumulative death counts") +
  ggtitle("Figure 3. Predicted vs true values for the outcome")

# predictions with linear regression 
set.seed(1)
rmse_linear <-replicate(1000, {
    y <- analysis_df$Total_deaths
    test_index <- createDataPartition(y, times = 1, p = 0.5, list = FALSE) 
    train_set <- analysis_df |> slice(-test_index) 
    test_set <- analysis_df |> slice(test_index) 
    fit <- lm(Total_deaths ~ Total_cases+ fully_vax_count+ Pop_millions+ Percent_Over_65 + km2+ GDP_per_capita + Obesity_rate + cvd_death_rate, data = train_set) 
    y_hat <- predict(fit, test_set)
    sqrt(mean((y_hat - test_set$Total_deaths)^2, na.rm = T)) 
})


hist(rmse_linear, main="Figure 4. Histogram of the RMSE across 1000 simulation \nusing a linear regression") 
mean(rmse_linear)
sd(rmse_linear)

mean(analysis_df$Total_deaths)

# predictions with knn machine learning 
set.seed(1)
rmse_knn <-replicate(1000, {
    y <- analysis_df$Total_deaths
    indexes = createDataPartition(analysis_df$Total_deaths, times = 1, p = 0.5, list = F)
    train = analysis_df[indexes, ] |> select(-c(Country, Total_deaths, Continent))
    test = analysis_df[-indexes, ] |> select(-c(Country, Total_deaths, Continent))
    test_outcome <- analysis_df[-indexes, ]|> pull(Total_deaths)
    train_outcome <- analysis_df[indexes, ]  |> pull(Total_deaths)
    reg_results <- knn.reg(train[complete.cases(train), ], test[complete.cases(test), ], train_outcome, k = 3)
    sqrt(mean((reg_results$pred - test_outcome[complete.cases(test) ])^2, na.rm = T)) 
})

hist(rmse_knn, main="Figure 5. Histogram of the RMSE across 1000 simulation \nusing kNN") 

mean(rmse_knn)
sd(rmse_knn)

```
