---
title: "References"
---


1. Ten health issues who will tackle this year (no date) World Health Organization. World Health Organization. Available at: https://www.who.int/news-room/spotlight/ten-threats-to-global-health-in-2019 (Accessed: December 15, 2022). 

2. Bill Gates: The next outbreak? We're not ready | TED Talk. Available at: https://www.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready?language=dz (Accessed: December 15, 2022).

3. Allam Z. The First 50 days of COVID-19: A Detailed Chronological Timeline and Extensive Review of Literature Documenting the Pandemic. Surveying the Covid-19 Pandemic and its Implications. 2020;1-7. doi:10.1016/B978-0-12-824313-8.00001-2

4. Walker, P.G.T.; Whittaker, C.; Watson, O.J.; Baguelin, M.; Winskill, P.; Hamlet, A.; Djafaara, B.A.; Cucunubá, Z.; Mesa, D.O.; Green, W.; et al. The impact of COVID-19 and strategies for mitigation and suppression in low- and middle-income countries. Science 2020, 369, 413–422.

5. ECA Report: Covid-19 in Africa: Protecting lives and economies | africa renewal (no date) United Nations. United Nations. Available at: https://www.un.org/africarenewal/news/coronavirus/eca-report-covid-19-africa-protecting-lives-and-economies (Accessed: December 15, 2022). 

6. Dessie ZG, Zewotir T. Mortality-related risk factors of COVID-19: a systematic review and meta-analysis of 42 studies and 423,117 patients. BMC Infect Dis. 2021;21(1):855. Published 2021 Aug 21. doi:10.1186/s12879-021-06536-3